name: Auto Update meta.json Daily

on:
  schedule:
    - cron: '0 4 * * *'  # every day at 4:00 AM UTC
  workflow_dispatch:

jobs:
  update-meta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run meta updater
        run: python update_meta.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}
        run: |
          git config user.name "Meta Bot"
          git config user.email "bot@clashmeta.com"
          git add meta.json
          git commit -m "🤖 Auto-update meta.json [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${REPO}.git
          git push origin HEAD:main
